---

- name: gather facts
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: gather apt facts
      package_facts:
        manager: apt

- name: virtualbox
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: install virtualbox if absent
      block:
        - name: check setup folder
          stat:
            path: ./setup/
          register: setup_folder
        - name: create setup folder
          when: not setup_folder.stat.exists
          local_action:
            module: shell
            _raw_params: mkdir setup
        - name: check virtualbox deb file
          stat:
            path: ./setup/virtualbox-7.0_7.0.10-158379~Ubuntu~jammy_amd64.deb
          register: vbox_setup_deb
        - name: install vbox setup file
          when: not vbox_setup_deb.stat.exists
          local_action:
            module: shell
            _raw_params: cd setup && curl -O https://download.virtualbox.org/virtualbox/7.0.10/virtualbox-7.0_7.0.10-158379~Ubuntu~jammy_amd64.deb
        - name: install vbox deb
          local_action:
            module: shell
            _raw_params: apt install -y `pwd`/setup/virtualbox-7.0_7.0.10-158379~Ubuntu~jammy_amd64.deb

      when: '"virtualbox-7.0" not in ansible_facts.packages'

- name: vagrant
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: install vagrant if absent
      block:
        - name: check setup folder
          stat:
            path: ./setup/
          register: setup_folder
        - name: create setup folder
          when: not setup_folder.stat.exists
          local_action:
            module: shell
            _raw_params: mkdir setup
        - name: check vagrant deb file
          stat:
            path: ./setup/vagrant_2.3.7-1_i686.deb
          register: vagrant_setup_deb
        - name: install vagrant setup file
          when: not vagrant_setup_deb.stat.exists
          local_action:
            module: shell
            _raw_params: cd setup && curl -O https://releases.hashicorp.com/vagrant/2.3.7/vagrant_2.3.7-1_i686.deb
        - name: install vagrant deb
          local_action:
            module: shell
            _raw_params: apt install -y `pwd`/setup/vagrant_2.3.7-1_i686.deb

      when: '"vagrant" not in ansible_facts.packages'

- name: virtual machines
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: vagrant up --provision
      local_action:
        module: shell
        _raw_params: cd k8s && vagrant up --provision

- name: Jenkins and Docker repo machine
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: vagrant up --provision
      local_action:
        module: shell
        _raw_params: cd j-repo && vagrant up --provision

- hosts: all
  tasks:
  - name: Generate SSH keys
    shell: ssh-keygen -q -t rsa -f /home/vagrant/.ssh/id_rsa -N ''
    args:
      creates: /home/vagrant/.ssh/id_rsa

  - name: Allow passwordless SSH to vms
    shell: /bin/cat /home/vagrant/.ssh/id_rsa.pub
    register: ssh_keys

  - name: Allow passwordless SSH between all hosts
    lineinfile:
      dest: /home/vagrant/.ssh/authorized_keys
      state: present
      line:  " {{ hostvars[item]['ssh_keys']['stdout'] }}"
    with_items: "{{ groups['all']}}"

- hosts: jenkins
  become: true
  tasks:
  - name: copy id_rsa to somewhere jenkins can reach
    shell: cp /home/vagrant/.ssh/id_rsa /home/ && chmod 777 /home/id_rsa
  
